add version 19.07.10

diff --git a/package/system/zram-swap/files/zram.init b/package/system/zram-swap/files/zram.init
--- a/package/system/zram-swap/files/zram.init
+++ b/package/system/zram-swap/files/zram.init
@@ -2,8 +2,9 @@
 
 START=15
 
-extra_command "compact" "Trigger compaction for all zram swap devices"
-extra_command "status" "Print out information & statistics about zram swap devices"
+EXTRA_COMMANDS="compact status"
+EXTRA_HELP="        compact trigger compaction for all Z-RAM swap dev's
+        status  print out status information & statistics about Z-RAM swap devices"
 
 ram_getsize()
 {
@@ -23,6 +24,31 @@ zram_getsize()	# in megabytes
 	else
 		echo "$zram_size"
 	fi
+}
+
+zram_applicable()
+{
+	local zram_dev="$1"
+
+	[ -e "$zram_dev" ] || {
+		logger -s -t zram_applicable -p daemon.crit "[ERROR] device '$zram_dev' not found"
+		return 1
+	}
+
+	which mkswap >/dev/null || {
+		logger -s -t zram_applicable -p daemon.err "[ERROR] 'mkswap' not installed"
+		return 1
+	}
+
+	which swapon >/dev/null || {
+		logger -s -t zram_applicable -p daemon.err "[ERROR] 'swapon' not installed"
+		return 1
+	}
+
+	which swapoff >/dev/null || {
+		logger -s -t zram_applicable -p daemon.err "[ERROR] 'swapoff' not installed"
+		return 1
+	}
 }
 
 zram_dev()
@@ -47,7 +73,7 @@ zram_getdev()
 	local zdev=$( zram_dev )
 
 	if [ "$(mount | grep $zdev)" ]; then
-		local idx=$(cat /sys/class/zram-control/hot_add)
+		local idx=`cat /sys/class/zram-control/hot_add`
 		zdev="$( zram_dev $idx )"
 	fi
 
@@ -59,16 +85,28 @@ zram_comp_algo()
 	local dev="$1"
 	local zram_comp_algo="$( uci -q get system.@system[0].zram_comp_algo )"
 
-	if [ -z "$zram_comp_algo" ]; then
-		# default to lzo, which is always available
-		zram_comp_algo="lzo"
+	if [ -z "$zram_comp_algo" ] || [ ! -e /sys/block/$( basename $dev )/comp_algorithm ]; then
+		return 0
 	fi
 
-	if [ $(grep -c "$zram_comp_algo" /sys/block/$( basename $dev )/comp_algorithm) -ne 0 ]; then
-		logger -s -t zram_comp_algo -p daemon.debug "set compression algorithm '$zram_comp_algo' for zram '$dev'"
+	if [ `grep -c "$zram_comp_algo" /sys/block/$( basename $dev )/comp_algorithm` -ne 0 ]; then
+		logger -s -t zram_comp_algo -p daemon.debug "Set compression algorithm '$zram_comp_algo' for zram '$dev'"
 		echo $zram_comp_algo > "/sys/block/$( basename $dev )/comp_algorithm"
 	else
-		logger -s -t zram_comp_algo -p daemon.debug "compression algorithm '$zram_comp_algo' is not supported for '$dev'"
+		logger -s -t zram_comp_algo -p daemon.debug "Compression algorithm '$zram_comp_algo' is not supported for '$dev'"
+	fi
+}
+
+zram_comp_streams()
+{
+	local dev="$1"
+	local logical_cpus=$( grep -ci "^processor" /proc/cpuinfo )
+	[ $logical_cpus -gt 1 ] || return 1
+	local zram_comp_streams="$( uci -q get system.@system[0].zram_comp_streams )"
+	[ -n "$zram_comp_streams" ] && [ "$zram_comp_streams" -le "$logical_cpus" ] || zram_comp_streams=$logical_cpus
+	if [ -e /sys/block/$( basename $dev )/max_comp_streams ]; then
+		logger -s -t zram_comp_streams -p daemon.debug "Set max compression streams to '$zram_comp_streams' for zram '$dev'"
+		echo $zram_comp_streams > /sys/block/$( basename $dev )/max_comp_streams
 	fi
 }
 
@@ -79,10 +117,11 @@ zram_stats()
 
 	printf "\nGathering stats info for zram device \"$( basename "$1" )\"\n\n"
 
-	printf "ZRAM\n----\n"
+	printf "Z-RAM\n-----\n"
 	printf "%-25s - %s\n" "Block device" $zdev
 	awk '{ printf "%-25s - %d MiB\n", "Device size", $1/1024/1024 }' <$zdev/disksize
 	printf "%-25s - %s\n" "Compression algo" "$(cat $zdev/comp_algorithm)"
+	printf "%-25s - %s\n" "Compression streams" "$( cat $zdev/max_comp_streams)"
 
 	awk 'BEGIN { fmt = "%-25s - %.2f %s\n"
 		fmt2 = "%-25s - %d\n"
@@ -108,8 +147,8 @@ zram_compact()
 	# compact zram device (reduce memory allocation overhead)
 	local zdev="/sys/block/$( basename "$1" )"
 
-	local old_mem_used=$(awk '{print $3}' <$zdev/mm_stat)
-	local old_overhead=$(awk '{print $3-$2}' <$zdev/mm_stat)
+	local old_mem_used=`awk '{print $3}' <$zdev/mm_stat`
+	local old_overhead=`awk '{print $3-$2}' <$zdev/mm_stat`
 
 	echo 1 > $zdev/compact
 
@@ -125,37 +164,23 @@ zram_compact()
 
 start()
 {
-	[ -e /proc/swaps ] || {
-		logger -s -t zram_start -p daemon.crit "kernel doesn't support swap"
-		return 1
-	}
-
 	if [ $( grep -cs zram /proc/swaps ) -ne 0 ]; then
-		logger -s -t zram_start -p daemon.notice "zram swap is already mounted"
+		logger -s -t zram_start -p daemon.notice "[OK] zram swap is already mounted"
 		return 1
 	fi
-
-	local zram_dev="$( zram_getdev )"
-
-	[ -e "$zram_dev" ] || {
-		logger -s -t zram_start -p daemon.crit "[ERROR] device '$zram_dev' not found"
-		return 1
-	}
 
 	local zram_size="$( zram_getsize )"
-	local zram_priority="$( uci -q get system.@system[0].zram_priority )"
+	local zram_dev="$( zram_getdev )"
+	zram_applicable "$zram_dev" || return 1
 
-	if [ -z "$zram_priority" ]; then
-		zram_priority="100"
-	fi
-
-	logger -s -t zram_start -p daemon.debug "activating '$zram_dev' for swapping ($zram_size MiB)"
+	logger -s -t zram_start -p daemon.debug "activating '$zram_dev' for swapping ($zram_size MegaBytes)"
 
 	zram_reset "$zram_dev" "enforcing defaults"
 	zram_comp_algo "$zram_dev"
+	zram_comp_streams "$zram_dev"
 	echo $(( $zram_size * 1024 * 1024 )) >"/sys/block/$( basename "$zram_dev" )/disksize"
-	busybox mkswap "$zram_dev"
-	busybox swapon -d -p $zram_priority "$zram_dev"
+	mkswap "$zram_dev"
+	swapon "$zram_dev"
 }
 
 stop()
@@ -164,7 +189,7 @@ stop()
 
 	for zram_dev in $( grep zram /proc/swaps |awk '{print $1}' ); do {
 		logger -s -t zram_stop -p daemon.debug "deactivate swap $zram_dev"
-		busybox swapoff "$zram_dev" && zram_reset "$zram_dev" "claiming memory back"
+		swapoff "$zram_dev" && zram_reset "$zram_dev" "claiming memory back"
 		local dev_index="$( echo $zram_dev | grep -o "[0-9]*$" )"
 		if [ $dev_index -ne 0 ]; then
 			logger -s -t zram_stop -p daemon.debug "removing zram $zram_dev"
diff --git a/scripts/config/Makefile b/scripts/config/Makefile
--- a/scripts/config/Makefile
+++ b/scripts/config/Makefile
@@ -1,154 +1,107 @@
-# SPDX-License-Identifier: GPL-2.0-only
 # ===========================================================================
 # OpenWrt configuration targets
-
-.PHONY: clean all
-all: conf mconf
-clean:
-	rm -f *.o lxdialog/*.o *.moc .*.cmd $(clean-files)
-
-# This clean-files definition is here to ensure that temporary files from the
-# previous version are removed by make config-clean.
-# It should be emptied after the end of support for OpenWrt 19.07.
-clean-files	:= zconf.tab.c zconf.lex.c zconf.hash.c .tmp_qtcheck
+# These targets are used from top-level makefile
 
 # ===========================================================================
-# Variables needed by the upstream Makefile
-
-# Avoids displaying 'UPD mconf-cfg' in an otherwise quiet make menuconfig
-kecho:=true
-
-CONFIG_SHELL:=$(SHELL)
-srctree:=.
-src:=.
-obj:=.
-Q:=$(if $V,,@)
-cmd = $(cmd_$(1))
-
-# some definitions taken from ../Kbuild.include
-dot-target = $(dir $@).$(notdir $@)
-squote  := '
-escsq = $(subst $(squote),'\$(squote)',$1)
-define filechk
-	$(Q)set -e;						\
-	mkdir -p $(dir $@);					\
-	trap "rm -f $(dot-target).tmp" EXIT;			\
-	{ $(filechk_$(1)); } > $(dot-target).tmp;		\
-	if [ ! -r $@ ] || ! cmp -s $@ $(dot-target).tmp; then	\
-		$(kecho) '  UPD     $@';			\
-		mv -f $(dot-target).tmp $@;			\
-	fi
-endef
-cmd-check = $(if $(strip $(cmd_$@)),,1)
-make-cmd = $(call escsq,$(subst $(pound),$$(pound),$(subst $$,$$$$,$(cmd_$(1)))))
-newer-prereqs = $(filter-out $(PHONY),$?)
-if_changed = $(if $(newer-prereqs)$(cmd-check),			\
-	$(cmd);							\
-	printf '%s\n' 'cmd_$@ := $(make-cmd)' > $(dot-target).cmd, @:)
-
-### Stripped down upstream Makefile follows:
-# ===========================================================================
+# Shared Makefile for the various kconfig executables:
+# conf:	  Used for defconfig, oldconfig and related targets
+# mconf:  Used for the mconfig target.
+#         Utilizes the lxdialog package
+# qconf:  Used for the xconfig target
+#         Based on Qt which needs to be installed to compile it
 # object files used by all kconfig flavours
-common-objs	:= confdata.o expr.o lexer.lex.o menu.o parser.tab.o \
-		   preprocess.o symbol.o util.o
 
-$(obj)/lexer.lex.o: $(obj)/parser.tab.h
-HOSTCFLAGS_lexer.lex.o	:= -I $(srctree)/$(src)
-HOSTCFLAGS_parser.tab.o	:= -I $(srctree)/$(src)
 
-# conf: Used for defconfig, oldconfig and related targets
-hostprogs	+= conf
-conf-objs	:= conf.o $(common-objs)
+# Platform specific fixes
+#
+# FreeBSD
 
-# nconf: Used for the nconfig target based on ncurses
-hostprogs	+= nconf
-nconf-objs	:= nconf.o nconf.gui.o $(common-objs)
+check_lxdialog = $(shell $(SHELL) $(CURDIR)/lxdialog/check-lxdialog.sh -$(1))
+export CFLAGS += -DKBUILD_NO_NLS -I. $(call check_lxdialog,ccflags)
+export CXXFLAGS += -DKBUILD_NO_NLS
 
-HOSTLDLIBS_nconf	= $(shell . $(obj)/nconf-cfg && echo $$libs)
-HOSTCFLAGS_nconf.o	= $(shell . $(obj)/nconf-cfg && echo $$cflags)
-HOSTCFLAGS_nconf.gui.o	= $(shell . $(obj)/nconf-cfg && echo $$cflags)
+conf-objs	:= conf.o zconf.tab.o
+mconf-objs	:= mconf.o zconf.tab.o
+qconf-cxxobjs	:= qconf.o
+qconf-objs	:= zconf.tab.o
 
-$(obj)/nconf.o $(obj)/nconf.gui.o: $(obj)/nconf-cfg
+lxdialog-objs := \
+	lxdialog/checklist.o lxdialog/util.o lxdialog/inputbox.o \
+	lxdialog/textbox.o lxdialog/yesno.o lxdialog/menubox.o
 
-# mconf: Used for the menuconfig target based on lxdialog
-hostprogs	+= mconf
-lxdialog	:= $(addprefix lxdialog/, \
-		     checklist.o inputbox.o menubox.o textbox.o util.o yesno.o)
-mconf-objs	:= mconf.o $(lxdialog) $(common-objs)
+clean-files	:= zconf.tab.c zconf.lex.c zconf.hash.c
+# Remove qconf junk files
+clean-files	+= $(qconf-cxxobjs) qconf.moc .tmp_qtcheck qconf
 
-HOSTLDLIBS_mconf = $(shell . $(obj)/mconf-cfg && echo $$libs)
-$(foreach f, mconf.o $(lxdialog), \
-  $(eval HOSTCFLAGS_$f = $$(shell . $(obj)/mconf-cfg && echo $$$$cflags)))
+all: conf mconf
 
-$(addprefix $(obj)/, mconf.o $(lxdialog)): $(obj)/mconf-cfg
-
-# qconf: Used for the xconfig target based on Qt
-hostprogs	+= qconf
-qconf-cxxobjs	:= qconf.o qconf-moc.o
-qconf-objs	:= images.o $(common-objs)
-
-HOSTLDLIBS_qconf	= $(shell . $(obj)/qconf-cfg && echo $$libs)
-HOSTCXXFLAGS_qconf.o	= $(shell . $(obj)/qconf-cfg && echo $$cflags)
-HOSTCXXFLAGS_qconf-moc.o = $(shell . $(obj)/qconf-cfg && echo $$cflags)
-
-$(obj)/qconf.o: $(obj)/qconf-cfg
-
-quiet_cmd_moc = MOC     $@
-      cmd_moc = $(shell . $(obj)/qconf-cfg && echo $$moc) $< -o $@
-
-$(obj)/qconf-moc.cc: $(src)/qconf.h $(obj)/qconf-cfg FORCE
-	$(call if_changed,moc)
-
-targets += qconf-moc.cc
-
-# check if necessary packages are available, and configure build flags
-filechk_conf_cfg = $(CONFIG_SHELL) $<
-
-$(obj)/%conf-cfg: $(src)/%conf-cfg.sh FORCE
-	$(call filechk,conf_cfg)
-
-clean-files += *conf-cfg
-
-# ===========================================================================
-# OpenWrt rules and final adjustments that need to be made after reading the
-# full upstream Makefile
-
-clean-files += $(targets) $(hostprogs)
-
-FORCE:
-
-ifdef BUILD_SHIPPED_FILES
-shipped-files := lexer.lex.c parser.tab.c parser.tab.h
-clean-files += $(shipped-files)
-
-.SECONDARY: $(shipped-files)
-
-%.tab.c %.tab.h: %.y
-	bison -l -d -b $* $<
-
-%.lex.c: %.l
-	flex -L -o$@ $<
+conf: $(conf-objs)
+mconf: $(mconf-objs) $(lxdialog-objs)
+	$(CC) -o $@ $^ $(call check_lxdialog,ldflags $(CC))
+qconf: $(qconf-cxxobjs) $(qconf-objs)
+ifneq ($(DISTRO-PKG-CONFIG),)
+	$(CXX) -o $@ $^ $(HOSTLOADLIBES_qconf)
+else
+	echo "You don't have 'pkg-config' installed. Cannot continue"
+	echo "For now, you may use 'make menuconfig' instead of 'make xconfig'"
 endif
 
-$(foreach f,$(conf-objs) $(filter-out $(common-objs),$(mconf-objs) \
-						     $(qconf-objs) \
-						     $(nconf-objs)), \
-  $(eval $(obj)/$f: CFLAGS+=$$(HOSTCFLAGS_$f)))
+clean:
+	rm -f *.o lxdialog/*.o $(clean-files) conf mconf
 
-$(foreach f,$(qconf-cxxobjs), \
-  $(eval $(obj)/$f: CXXFLAGS+=$$(HOSTCXXFLAGS_$f)))
+zconf.tab.o: zconf.lex.c zconf.hash.c confdata.c
 
-$(obj)/conf: $(addprefix $(obj)/,$(conf-objs))
+kconfig_load.o: lkc_defs.h
 
-# The *conf-cfg file is used (then filtered out) as the first prerequisite to
-# avoid sourcing it before the script is built, when trying to compute CFLAGS
-# for the actual first prerequisite.  This avoids errors like:
-# '/bin/sh: ./mconf-cfg: No such file or directory'
-$(obj)/mconf: mconf-cfg $(addprefix $(obj)/,$(mconf-objs))
-	$(CC) -o $@ $(filter-out mconf-cfg,$^) $(HOSTLDLIBS_mconf)
+zconf.tab.c: zconf.y $(wildcard zconf.tab.c_shipped)
+zconf.lex.c: zconf.l $(wildcard zconf.lex.c_shipped)
+zconf.hash.c: zconf.gperf $(wildcard zconf.hash.c_shipped)
 
-$(obj)/nconf: nconf-cfg $(addprefix $(obj)/,$(nconf-objs))
-	$(CC) -o $@ $(filter-out nconf-cfg,$^) $(HOSTLDLIBS_nconf)
+%.tab.c: %.y
+	cp $@_shipped $@ || bison -l -b $* -p $(notdir $*) $<
 
-$(obj)/qconf: qconf-cfg $(addprefix $(obj)/,$(qconf-cxxobjs) $(qconf-objs))
-	$(CXX) -o $@ $(filter-out qconf-cfg,$^) $(HOSTLDLIBS_qconf)
+%.lex.c: %.l
+	cp $@_shipped $@ || flex -L -P$(notdir $*) -o$@ $<
+
+%.hash.c: %.gperf
+	cp $@_shipped $@ || gperf < $< > $@
+
+ifeq ($(MAKECMDGOALS),qconf)
+qconf.o: .tmp_qtcheck
+.tmp_qtcheck: Makefile
+-include .tmp_qtcheck
+
+# Qt needs some extra effort...
+.tmp_qtcheck:
+	@set -e; echo "  CHECK   qt"; \
+	if $(DISTRO-PKG-CONFIG) --exists Qt5Core; then \
+	    cflags="-std=c++11 -fPIC `$(DISTRO-PKG-CONFIG) --cflags Qt5Core Qt5Gui Qt5Widgets`"; \
+	    libs=`$(DISTRO-PKG-CONFIG) --libs Qt5Core Qt5Gui Qt5Widgets`; \
+	    moc=`$(DISTRO-PKG-CONFIG) --variable=host_bins Qt5Core`/moc; \
+	elif $(DISTRO-PKG-CONFIG) --exists QtCore; then \
+	    cflags=`$(DISTRO-PKG-CONFIG) --cflags QtCore QtGui`; \
+	    libs=`$(DISTRO-PKG-CONFIG) --libs QtCore QtGui`; \
+	    moc=`$(DISTRO-PKG-CONFIG) --variable=moc_location QtCore`; \
+	else \
+	    echo >&2 "*"; \
+	    echo >&2 "* Could not find Qt via $(DISTRO-PKG-CONFIG)."; \
+	    echo >&2 "* Please install either Qt 4.8 or 5.x. and make sure it's in PKG_CONFIG_PATH"; \
+	    echo >&2 "*"; \
+	    exit 1; \
+	fi; \
+	echo "KC_QT_CFLAGS=$$cflags" > $@; \
+	echo "KC_QT_LIBS=$$libs" >> $@; \
+	echo "KC_QT_MOC=$$moc" >> $@
+endif
+
+#Define compiler flags to build qconf
+HOSTLOADLIBES_qconf	= $(KC_QT_LIBS)
+HOSTCXXFLAGS_qconf.o	= $(KC_QT_CFLAGS)
+
+qconf.o: qconf.moc
+qconf.o: CXXFLAGS+=$(HOSTCXXFLAGS_qconf.o)
+
+moc = $(KC_QT_MOC) -i $< -o $@
+
+%.moc: %.h .tmp_qtcheck
+	$(call moc)
